cnn_qp1_mpii('modelType', 'fcn32s', 'alpha', 0.5, ...
             'batchSize', 60, 'learningRate', 1e-6, ...
             'numEpochs', 25);
cnn_qp1_mpii('modelType', 'fcn16s', 'alpha', 0.5, ...
             'batchSize', 60, 'learningRate', 1e-6, ...
             'numEpochs', 9);
cnn_qp1_mpii('modelType', 'fcn8s', 'alpha', 0.5, ...
             'batchSize', 60, 'learningRate', 1e-6, ...
             'numEpochs', 1);
cnn_qp1_mpii('modelType', 'fcn4s', 'alpha', 0.5, ...
             'batchSize', 60, 'learningRate', 1e-6, ...
             'numEpochs', 1);
