cnn_qp2_mpii('modelType', 'fcn16s', 'alpha', 0.5, ...
                  'batchSize', 50, 'learningRate', 1e-6, ...
                  'numEpochs', 10);
cnn_qp2_mpii('modelType', 'fcn8s', 'alpha', 0.5, ...
                 'batchSize', 50, 'learningRate', 1e-6, ...
                 'numEpochs', 1);
cnn_qp2_mpii('modelType', 'fcn4s', 'alpha', 0.5, ...
                  'batchSize', 40, 'learningRate', 1e-6, ...
                  'numEpochs', 5);
